CREATE TABLE BUDGET_USE(
  PLAN_YM VARCHAR2(6),
  DEPT_CODE VARCHAR2(10),
  SEQ NUMBER(10, 0),
  EDI_CODE VARCHAR2(20) NOT NULL,
  USE_BUDGET NUMBER(10, 0) DEFAULT 0,
  USE_DATE DATE NOT NULL,
  INP_DATE DATE DEFAULT SYSDATE,
  UPDATE_DATE DATE DEFAULT SYSDATE,
  CONSTRAINT PK_BUDGET_USE PRIMARY KEY(PLAN_YM, DEPT_CODE, SEQ)
);