/*코드한글명 매핑테이블*/
CREATE TABLE COMMON_CODE_MAP (
    COLUMN_ID VARCHAR2(100),
    CODE_ID VARCHAR2(1000),
    CODE_NAME VARCHAR2(1000),
    INP_DATE DATE DEFAULT SYSDATE,
    UPDATE_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_COMMON_CODE_MAP PRIMARY KEY(COLUMN_ID, CODE_ID)
);