CREATE TABLE EDI_WORK_DAY (
    EDI_CODE VARCHAR2(20) PRIMARY KEY,
    EDI_EMP_CODE VARCHAR2(10),
    EDI_WORK_TYPE VARCHAR2(2),
    EDI_WORK_DATE DATE,
    INP_DATE DATE DEFAULT SYSDATE,
    UPDATE_DATE DATE DEFAULT SYSDATE
);