CREATE TABLE EMP_SCHEDULE(
  EMP_CODE VARCHAR2(10),
  SCHEDULE_DATE DATE,
  SCHEDULE_STATUS VARCHAR2(10) NOT NULL,
  OVERTIME_START DATE,
  OVERTIME_END DATE,
  OVERTIME_HOUR NUMBER(10,0),
  INP_DATE DATE DEFAULT SYSDATE,
  UPDATE_DATE DATE DEFAULT SYSDATE,
  CONSTRAINT PK_EMP_SCHEDULE PRIMARY KEY(EMP_CODE, SCHEDULE_DATE)
);